export interface IEvent {
  id: number,
  title: string,
  date: string,
  datec: string,
  category: string,
  day : string,
  month : string,
  site: string,
  image: string,
  city: string,
  year: string,
  tickets: string,
  time: string,
  banner: string,
  price: string,
  map: string,
}
